name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Configure matchers
          uses: mheap/phpunit-matcher-action@v1
        - name: Configure Composer
          uses: php-actions/composer@v5
        - name: Run PHPUnit tests
          uses: php-actions/phpunit@v3
          with:
            configuration: test/phpunit.xml
            args: --teamcity
          env:
            XDEBUG_MODE: coverage